### ISSUE TITLE
Python 3.7 compatibility ('tesbml' dependency in setup.py)

### ISSUE THREAD

**Issue by gglyptodon** [sys-bio/simplesbml#25]
It looks like the package python-libsbml works as replacement for tesbml, which is listed as a requirement.
python-libsbml can be installed via pip on python 3.7 while tesbml is unavailable. Would it make sense to swap python-libsbml for tesbml in the setup.py / requirements.txt ? Thanks.

**Comment by andrewbriand** [comment]
Yes, that would make sense. I will look into making tesbml available for 3.7.

**Comment by hsauro** [comment]
We no longer use tesbml (thank goodness)  and python-libsbml now the package we use.
